language: cpp

env:
  global:
  - ExternalData_OBJECT_STORES="${HOME}/.ExternalData"
  - PROJ_SRC="${TRAVIS_BUILD_DIR}"
  - ITK_MODULE_NAME=SimpleITKFiltersModule
  - ITK_TAG=master
  - ITK_SRC="${HOME}/ITK"

cache:
  directories:
    - ${ExternalData_OBJECT_STORES}

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      env: CI_CXX=g++-6 CI_CCC=gcc-6
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
          # add PPAs with more up-to-date toolchains
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
    - os: linux
      env: CI_CXX=g++-5 CI_CCC=gcc-5
      sudo: required
      dist: trusty
      addons:
        sources:
          # add PPAs with more up-to-date toolchains
            - ubuntu-toolchain-r-test
        apt:
          packages:
            - g++-5
    - os: osx
      osx_image: xcode7.3


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja $( command -V cmake &>2 /dev/null || echo "cmake" ); fi

before_script:
   - cmake --version
   - if [[ -n "$CI_CC" ]]; then export CC="$CI_CC"; fi
   - if [[ -n "$CI_CXX" ]]; then export CXX="$CI_CXX"; fi
   - ls -la $(which $CXX)
   - $CXX --version
   - env
   - bash -x ${PROJ_SRC}/test/ci/CacheAndUpdateITK.sh

script:
   - ctest -V -S ${PROJ_SRC}/test/ci/travis_dashboard.cmake
